const BookingAction = {
    GET_ROOM_TO_CART: 'GET_ROOM_TO_CART',
    BOOKING_START: 'BOOKING_START',
    PAYMENT: 'PAYMENT',
    SAVE_INVOICE: 'SAVE_INVOICE',
    RESERVATION_DETAIL: 'RESERVATION_DETAIL',
}
export default BookingAction